modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="undertale_mod"
version="1.0.0"
displayName="Undertale Mod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="SuperFrancy 0171, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.undertale_mod]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.undertale_mod]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration